
from .core import slot

VEHICLE = [
    slot("vehicle_condition", "New or used", 5, "choice",
         "New, used, or demo; drives valuation and age limits",
         options=["new", "used", "demo"], group="asset"),
    slot("vehicle_make_model", "Make and model", 5, "text",
         "What they are buying", group="asset"),
    slot("vehicle_year", "Year of manufacture", 5, "number",
         "Age at end of term matters for used vehicles",
         validation={"min": 1990, "max": 2027}, group="asset"),
    slot("vehicle_purchase_price", "Purchase price", 5, "currency",
         "Price on the contract of sale or dealer invoice",
         validation={"min": 1000},
         verification="contract_of_sale", group="asset"),
    slot("seller_type", "Private or dealer sale", 5, "choice",
         "Dealer sales need an invoice with ABN; private sales need more checks",
         options=["dealer", "private"],
         verification="contract_of_sale", group="asset"),
    slot("vehicle_vin_or_rego", "VIN or registration number", 5, "text",
         "Identifies the security; skip if they have not chosen a vehicle yet",
         required=False,
         verification="contract_of_sale", group="asset"),
    slot("trade_in_or_deposit", "Trade-in or deposit amount", 5, "currency",
         "Reduces the amount financed; 0 if none",
         validation={"min": 0}, group="asset"),
    slot("wants_balloon", "Balloon payment preference", 5, "boolean",
         "Explain the trade-off before asking: lower repayments, "
         "but the lump sum keeps accruing interest so total cost is usually higher",
         regulatory_basis="NCCP requirements and objectives", group="asset"),
    slot("balloon_percentage", "Balloon as percent of price", 5, "number",
         "Only when they want one",
         required_when="wants_balloon == True",
         validation={"min": 0, "max": 50}, group="asset"),
]

_PROPERTY_BASE = [
    slot("property_found", "Property identified yet", 5, "boolean",
         "Still searching is a valid answer and changes what follows",
         group="property"),
    slot("property_address", "Property address", 5, "address",
         "Only once they have found one",
         required_when="property_found == True",
         verification="contract_of_sale", group="property"),
    slot("property_state", "State", 5, "choice",
         "Stamp duty and scheme rules vary by state",
         options=["NSW", "VIC", "QLD", "WA", "SA", "TAS", "ACT", "NT"],
         group="property"),
    slot("property_type", "Property type", 5, "choice",
         "Apartments, land and off-the-plan carry different lending limits",
         options=["house", "apartment", "townhouse", "land", "off_the_plan"],
         group="property"),
    slot("property_price", "Purchase price or estimated value", 5, "currency",
         "Their estimate is fine at this stage",
         validation={"min": 50000},
         verification="contract_of_sale", group="property"),
    slot("deposit_amount", "Deposit available", 5, "currency",
         "Determines LVR and whether LMI applies",
         validation={"min": 0},
         verification="bank_statements", group="property"),
    slot("deposit_source", "Source of deposit", 5, "choice",
         "Genuine savings are treated differently from a gift or an inheritance",
         options=["genuine_savings", "gift", "inheritance", "sale_of_asset",
                  "equity_release", "other"],
         verification="bank_statements",
         regulatory_basis="Lending policy — deposit verification", group="property"),
    slot("repayment_type", "Principal and interest or interest only", 5, "choice",
         "Ask what they prefer and why; this is a requirements conversation",
         options=["principal_and_interest", "interest_only"],
         regulatory_basis="NCCP requirements and objectives", group="loan"),
    slot("has_guarantor", "Guarantor involved", 5, "boolean",
         "A guarantor arrangement adds its own assessment path",
         required=False, group="property"),
]

HOME = _PROPERTY_BASE + [
    slot("first_home_buyer", "First home buyer", 5, "boolean",
         "Opens scheme eligibility questions",
         regulatory_basis="First home buyer schemes", group="property"),
    slot("scheme_interest", "Interested in a first home buyer scheme", 5, "boolean",
         "Only for first home buyers; schemes carry income and price caps "
         "that must be checked against current published thresholds",
         required_when="first_home_buyer == True",
         regulatory_basis="First home buyer schemes", group="property"),
    slot("deposit_savings_history", "How the deposit was saved", 5, "text",
         "First home buyers usually need evidence of consistent saving "
         "or a record of timely rent payments",
         required_when="first_home_buyer == True",
         verification="bank_statements", group="property"),
]

INVESTMENT = _PROPERTY_BASE + [
    slot("expected_weekly_rent", "Expected weekly rent", 5, "currency",
         "Rental income supports serviceability but is shaded by the lender",
         validation={"min": 0},
         verification="rental_appraisal", group="property"),
    slot("existing_investment_properties", "Investment properties already owned", 5, "number",
         "Portfolio size affects exposure limits",
         validation={"min": 0}, group="property"),
]

BUSINESS = [
    slot("business_name", "Registered business name", 5, "text",
         "As registered", verification="asic_extract", group="business"),
    slot("abn_or_acn", "ABN or ACN", 5, "text",
         "Identifies the entity",
         verification="asic_extract", group="business"),
    slot("entity_structure", "Entity structure", 5, "choice",
         "Drives which constituent documents are required",
         options=["sole_trader", "partnership", "company", "trust"],
         regulatory_basis="Entity verification", group="business"),
    slot("entity_documents_note", "Constituent documents", 5, "text",
         "Partnership agreement, trust deed or company constitution as applicable",
         required_when="entity_structure in ('partnership', 'company', 'trust')",
         verification="entity_documents", group="business"),
    slot("years_trading", "Years trading", 5, "number",
         "Minimum trading period is a policy screen",
         validation={"min": 0},
         verification="tax_return", group="business"),
    slot("annual_turnover", "Annual turnover", 5, "currency",
         "Most recent financial year",
         validation={"min": 0},
         verification="financial_statements", group="business"),
    slot("industry", "Industry", 5, "text",
         "Some industries are excluded by policy",
         regulatory_basis="Industry exclusions", group="business"),
    slot("use_of_funds", "Detailed use of funds", 5, "text",
         "Specific, not general — this is the strongest screen in business lending",
         regulatory_basis="NCCP requirements and objectives", group="business"),
    slot("existing_business_lending", "Existing business lending", 5, "text",
         "Cards, loans, overdrafts, equipment finance, guarantees, rental bonds",
         group="business"),
    slot("security_offered", "Security offered", 5, "text",
         "Property, business assets, or unsecured",
         group="business"),
    slot("director_guarantee_accepted", "Director guarantee understood", 5, "boolean",
         "Directors are normally required to guarantee personally, which means "
         "their personal position is assessed too — confirm they understand",
         regulatory_basis="Guarantor disclosure", group="business"),
]

OVERLAYS_BY_PRODUCT = {
    "PL-STD-001": [],
    "PL-SEC-002": [
        slot("security_asset", "Asset offered as security", 5, "text",
             "What they are securing the loan against",
             group="asset"),
        slot("security_asset_value", "Estimated value of the security", 5, "currency",
             "Their estimate; verified later",
             validation={"min": 0}, group="asset"),
    ],
    "HL-VAR-010": HOME,
    "HL-FIX-011": HOME,
    "VL-NEW-020": VEHICLE,
    "VL-USED-021": VEHICLE,
    "BL-TERM-030": BUSINESS,
    "IL-PROP-040": INVESTMENT,
}