"""bank hierarchy and notifications

Revision ID: e80fc8b39b2c
Revises: 2aec7d2b2343
Create Date: 2026-09-10 11:26:24.277332

"""
from alembic import op
import sqlalchemy as sa
import app.db.types  # noqa: F401 — needed whenever a migration touches an EncryptedString column


# revision identifiers, used by Alembic.
revision = 'e80fc8b39b2c'
down_revision = '2aec7d2b2343'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('max_approval_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('can_manage_staff', sa.Boolean(), nullable=False),
    sa.Column('can_manage_products', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('escalations', sa.Column('escalated_to_position_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'escalations', 'bank_positions', ['escalated_to_position_id'], ['id'])
    op.add_column('users', sa.Column('position_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'bank_positions', ['position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'position_id')
    op.drop_constraint(None, 'escalations', type_='foreignkey')
    op.drop_column('escalations', 'escalated_to_position_id')
    op.drop_table('notifications')
    op.drop_table('bank_positions')
    # ### end Alembic commands ###
